version: "3.8"
services:
  sonarqube:
    image: "sonarqube:8.3.1-community"
    healthcheck:
      # There's no 'curl' in the sonarqube's images, but 'wget' is present (BusyBox version!)
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://admin:admin@localhost:9000/api/system/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
    - "127.0.0.1:9000:9000"
