name: "Publish Release Artifacts"

on:
  release:
    types:
      - created

jobs:
  publish_artifacts:
    name: Publish final artifacts into GitHub Packages repo
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'lfr-solution-desk/')
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Publish final artifacts'
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x

          # run the verification task serparately, to make sure nothing gets
          # published (no subprojects) if there is one or more which would not be
          # able to be published
          ./gradlew verifyPublication

          ./gradlew publish \
              -Pliferay.gpr.publishing.actor=${GITHUB_ACTOR} \
              -Pliferay.gpr.publishing.token=${GITHUB_TOKEN} \
              -Pliferay.gpr.publishing.type=RELEASE
