name: "Main CI"

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'

jobs:
  sonarcloud:
    name: SonarCloud check + code coverage
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'lfr-solution-desk/')
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Analyze code with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_OPTS: "-XX:MaxMetaspaceSize=512m"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
              --no-daemon \
              --stacktrace \
              --warning-mode=all \
              -Dsonar.login=${SONAR_TOKEN}
