name: "Main CI"

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.repository, 'lfr-solution-desk/') && (startsWith(github.ref, 'refs/heads/releases/') || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Run tests'
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew check \
              --info \
              --full-stacktrace \
              -PenvironmentName=ci \
              -PgradleTest.liferay.gpr.publishing.actor=${GITHUB_ACTOR} \
              -PgradleTest.liferay.gpr.publishing.token=${GITHUB_TOKEN} \
              -PgradleTest.GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
              -PgradleTest.sonar.login=${SONAR_TOKEN}
