name: "Main CI"

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.repository, 'lfr-solution-desk/') && (startsWith(github.ref, 'refs/heads/releases/') || github.ref == 'refs/heads/master')
    strategy:
      matrix:
        jdk_version: [ 8 ]
        extraGradleArgs: [ '-x :sonar:check' ]
        # Add a matrix item to use JDK 11 with no test excluded
        include:
          - jdk_version: 11
            extraGradleArgs: ''

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK ${{ matrix.jdk_version }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk_version }}
      - name: 'Run tests'
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew check \
              ${{ matrix.extraGradleArgs }} \
              --info \
              --full-stacktrace \
              -PenvironmentName=ci \
              -PgradleTest.liferay.gpr.publishing.actor=${GITHUB_ACTOR} \
              -PgradleTest.liferay.gpr.publishing.token=${GITHUB_TOKEN} \
              -PgradleTest.GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
              -PgradleTest.sonar.login=${SONAR_TOKEN}
